title: Active Minds Yearn
description: >

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
include: ['_static', '_dynamic', 'uploads']
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
tag_page_layout: tag
tag_page_dir: tag
plugins:
- jekyll-menus
collections:
  posts:
    title: Post
    output: true
    permalink: /blog/:year-:month-:day-:title:output_ext
    layout: post
  inspiration:
    title: inspiration
    layout: inspiration_item
    output: true
    permalink: /inspiration/:year-:month-:day:output_ext
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "inspiration"
    values:
      layout: "inspiration_item"
pagination:
  enabled: true
  sort_reverse: true
  per_page: 6
  permalink: /:num/
  trail: 
    before: 2 # The number of links before the current page
    after: 2  # The number of links after the current page