title: Active Minds Yearn
description: >

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
collections:
  posts:
    title: Post
    output: true
    permalink: /blog/:year-:month-:day-:title:output_ext
    layout: post
  motivation:
    title: Motivation
    layout: motivation_item
    output: true
    permalink: /motivation/:year-:month-:day:output_ext
  uploads:
    title: Uploads
    output: false
tag_page_layout: tag
tag_page_dir: tag
plugins:
- jekyll-menus