---
label: Settings
hide_body: true
fields:
- type: field_group
  name: logo
  label: Logo
  fields:
  - type: file
    name: navigation
    label: Navigation Logo
    description: "<em>Required </em>The logo that appears in the top left."
  - type: file
    name: footer
    label: Footer Logo
    description: "<em>Required </em>The logo that appears in the footer."
  description: The logo of the site.
- type: field_group
  name: newsletter
  label: Newsletter
  fields:
  - type: text
    name: title
    label: Title
    description: The title of the newsletter box, encouraging people to subscribe
      to the newsletter.
    config:
      required: true
  - type: text
    name: description
    label: Description
    description: "<em>Required </em>The description in the newsletter box."
    config:
      required: true
  description: Customize the newsletter options.
- name: instagram_feed_title
  type: text
  config:
    required: true
  label: Instagram Feed Title
  default: Latest Instagram Posts
  description: "<em>Required </em>The title above the Instagram Feed."
- name: adsense_code
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: adsense_code
pages:
- _data/general.yml
